#Kavish Nag
#24070126085
#AIML B1

In [96]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import mean_squared_error,r2_score
from math import sqrt

In [97]:
df = sns.load_dataset('penguins')
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [98]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [99]:
df.shape

(344, 7)

In [100]:
df.dropna(inplace=True)
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [102]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,1
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,0
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,1

In [103]:
train, test = train_test_split(df, test_size = 0.3)
x_train = train.drop(['species', 'island','body_mass_g'], axis=1)
y_train = train['body_mass_g']

x_test = test.drop(['species', 'island','body_mass_g'], axis=1)
y_test = test['body_mass_g']

In [104]:
model = neighbors.KNeighborsRegressor(n_neighbors = 3)

model.fit(x_train, y_train)
pred=model.predict(x_test)
error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
error

348.20073233696684

In [105]:
rmse_val = [] #to store rmse values for different k
k_list=[]
for K in range(50):
    K = K+1
    model = neighbors.KNeighborsRegressor(n_neighbors = K)

    model.fit(x_train, y_train)  #fit the model
    pred=model.predict(x_test) #make prediction on test set
    error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
    rmse_val.append(error) #store rmse values
    k_list.append(K)

In [106]:
best_rmse_score=min(rmse_val)
best_k=k_list[rmse_val.index(best_rmse_score)]
print("Optimum K value=",best_k,"with least RMS=",best_rmse_score)

Optimum K value= 4 with least RMS= 314.6513447452593

In [107]:
model = neighbors.KNeighborsRegressor(n_neighbors = best_k)

model.fit(x_train, y_train)
pred=model.predict(x_test)

In [108]:
import sklearn.metrics as metrics
print("Accuracy:",metrics.r2_score(y_test,pred))
print("MAE     :",metrics.mean_absolute_error(y_test,pred))
print("MSE     :",metrics.mean_squared_error(y_test,pred))
print("RMSE    :",np.sqrt(metrics.mean_squared_error(y_test,pred)))

Accuracy: 0.8345990747457075
MAE     : 247.75
MSE     : 99005.46875
RMSE    : 314.6513447452593